/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package te.tris;

import java.awt.event.KeyEvent;

/**
 *
 * @author muszkie
 */

public class MinesweeperGame extends javax.swing.JFrame {
    public boolean gameOverFlag = false;
    public boolean gameOverMSGFlag = false;
    
    public boolean gameOver(){
        
        return gameOverFlag;
    }

    /**
     * Creates new form MinesweeperWindow
     */
    
    public MinesweeperGame() {
        initComponents();
    }

       
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        saperGra1 = new te.tris.minesweeperWindow();
        gameOverMSG = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jButton1.setText("Close");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout saperGra1Layout = new javax.swing.GroupLayout(saperGra1);
        saperGra1.setLayout(saperGra1Layout);
        saperGra1Layout.setHorizontalGroup(
            saperGra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        saperGra1Layout.setVerticalGroup(
            saperGra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );

        gameOverMSG.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(saperGra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap(227, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(gameOverMSG, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(22, 22, 22)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gameOverMSG, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(saperGra1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
                
        if(saperGra1.gameOver()){
            jLabel1.setText("Game Over");
            gameOverMSG.setText("press enter to continue");
            gameOverMSGFlag=true;
        }
        
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_LEFT:
                if(saperGra1.current.x > 1){
                saperGra1.current.x-=1;
                saperGra1.repaint();
                }
                break;
            case KeyEvent.VK_RIGHT:
                if(saperGra1.current.x < 10){
                saperGra1.current.x+=1;
                saperGra1.repaint();
                }
                break;
            case KeyEvent.VK_DOWN:
                if(saperGra1.current.y < 10){
                saperGra1.current.y+=1;     
                saperGra1.repaint();
                }
                break;
            case KeyEvent.VK_UP:
                if(saperGra1.current.y > 1){
                saperGra1.current.y-=1;
                saperGra1.repaint();
                }
                break;
            case KeyEvent.VK_SPACE:
                saperGra1.setBombFound();
                if(saperGra1.gameWin()){
                    jLabel1.setText("You Won");
                    gameOverMSG.setText("press enter to continue");
                    gameOverMSGFlag=true;
                }
                
                break;
            case KeyEvent.VK_ENTER:
                if(gameOverMSGFlag){
                    gameOverFlag = true;
                }
                saperGra1.setVisited();
            if(saperGra1.gameOver()){
            jLabel1.setText("Game Over");
            gameOverMSG.setText("press enter to continue");
            saperGra1.clickCount = 999;
            gameOverMSGFlag=true;
        }

                
            default:
                break;
        }
    }//GEN-LAST:event_formKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        saperGra1.reset();
        if(jLabel1.getText()!="You Won"){
            saperGra1.clickCount = 999;
        }
        gameOverFlag = true;

        
    }//GEN-LAST:event_jButton1ActionPerformed
    public void reset(){
        saperGra1.reset();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MinesweeperGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MinesweeperGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MinesweeperGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MinesweeperGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MinesweeperGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gameOverMSG;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private te.tris.minesweeperWindow saperGra1;
    // End of variables declaration//GEN-END:variables

    int getScore() {
        return saperGra1.clickCount;
    }

    void resetScore() {
        saperGra1.clickCount=999;
    }
}
